set number
set ruler
set autowrite

"tabstop
set tabstop=4
set shiftwidth=4

set expandtab

" fix backspace
set backspace=indent,eol,start

" Needed for autoformatting in Rust
filetype plugin on

"Color Scheme
syntax on
set background=dark
let g:gruvbox_contrast_dark = "hard"
colo gruvbox-modified

set hlsearch " move to color scheme

set statusline=
set statusline+=%f
set statusline+=\ %l:%c


"linting
let g:ale_linters_explicit = 1

let g:ale_linter_aliases = {
\  'typescriptreact': 'typescript',
\  'javascriptreact': 'javascript',
\}

let g:ale_linters = {
\   'rust': ['cargo', 'rls'],
\}


let g:ale_fixers = {
\  'javascript': ['prettier', 'eslint'],
\  'typescript': ['prettier', 'eslint'],
\  'rust': ['rustfmt'],
\}

let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
inoremap <silent> <C-N> <C-\><C-O>:ALEComplete<CR>

command D ALEGoToDefinition
command I ALEHover
command T ALEGoToTypeDefinition
command E ALEDetail
command C ALEReset
command Rename ALERename

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Leaders
let mapleader=","
nmap <Leader>p :CtrlP<CR>

" Ctrlp ignore node modules
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
