set number
set ruler
set autowrite

"tabstop
set tabstop=4
set shiftwidth=4

set expandtab

" fix backspace
set backspace=indent,eol,start

" Needed for autoformatting in Rust
filetype plugin on

"Color Scheme
syntax on
set background=dark
let g:gruvbox_contrast_dark = "hard"
colo gruvbox-modified

set hlsearch " move to color scheme

set statusline=
set statusline+=%f
set statusline+=\ %l:%c


"linting
let g:ale_fixers = {
\  'javascript': ['prettier', 'eslint'],
\  'typescript': ['prettier', 'eslint'],
\  'typescriptreact': ['prettier', 'eslint'],
\}

let g:ale_fix_on_save = 1

" Rust
let g:rustfmt_autosave = 1

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Leaders
let mapleader=","
nmap <Leader>p :CtrlP<CR>

" Ctrlp ignore node modules
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
